=== Evangileon/DistributedFileSystem/configs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="configs" type="configsType"/>
  <xs:complexType name="metaServerType">
    <xs:sequence>
      <xs:element type="xs:string" name="hostname"/>
      <xs:element type="xs:integer" name="receiveHeartbeatPort"/>
      <xs:element type="xs:integer" name="clientPort"/>
      <xs:element type="xs:integer" name="ackPort"/>
      <xs:element type="xs:integer" name="replicaPort"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="configsType">
    <xs:sequence>
      <xs:element type="metaServerType" name="metaServer"/>
      <xs:element type="fileServersType" name="fileServers"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fileServersType">
    <xs:sequence>
      <xs:element type="fileServerType" name="fileServer" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fileServerType">
    <xs:sequence>
      <xs:element name="id" type="xs:integer"/>
      <xs:element name="hostname" type="xs:string"/>
      <xs:element type="xs:integer" name="receiveMetaFilePort"/>
      <xs:element type="xs:integer" name="requestFilePort"/>
      <xs:element type="xs:integer" name="commandPort"/>
      <xs:element name="storageDir" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Evangileon/DistributedFileSystem/configs.xml
<?xml version="1.0" encoding="UTF-8"?>
<configs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="configs.xsd">
    <metaServer>
        <hostname>dc02.utdallas.edu</hostname>
        <receiveHeartbeatPort>50001</receiveHeartbeatPort>
        <clientPort>50003</clientPort>
        <ackPort>50006</ackPort>
        <replicaPort>50007</replicaPort>
    </metaServer>

    <fileServers>
        <fileServer>
            <id>1</id>
            <hostname>dc03.utdallas.edu</hostname>
            <receiveMetaFilePort>50002</receiveMetaFilePort>
            <requestFilePort>50004</requestFilePort>
            <commandPort>50005</commandPort>
            <storageDir>files1</storageDir>
        </fileServer>
        <fileServer>
            <id>2</id>
            <hostname>dc05.utdallas.edu</hostname>
            <receiveMetaFilePort>50002</receiveMetaFilePort>
            <requestFilePort>50004</requestFilePort>
            <commandPort>50005</commandPort>
            <storageDir>files2</storageDir>
        </fileServer>
        <fileServer>
            <id>3</id>
            <hostname>dc08.utdallas.edu</hostname>
            <receiveMetaFilePort>50002</receiveMetaFilePort>
            <requestFilePort>50004</requestFilePort>
            <commandPort>50005</commandPort>
            <storageDir>files3</storageDir>
        </fileServer>
    </fileServers>

</configs>
